import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:recase/recase.dart';

/// Writes generated code files to the output directory.
class FileWriter {
  final String outputDirectory;

  FileWriter(this.outputDirectory);

  /// Ensures the output directory structure exists.
  void ensureDirectories() {
    for (final subDir in ['models', 'responses', 'clients', 'providers']) {
      Directory(p.join(outputDirectory, subDir)).createSync(recursive: true);
    }
  }

  /// Writes a model file.
  void writeModel(String schemaName, String code) {
    final fileName = '${ReCase(schemaName).snakeCase}.dart';
    _writeFile(p.join(outputDirectory, 'models', fileName), code);
  }

  /// Writes a response file.
  void writeResponse(String operationId, String code) {
    final fileName = '${ReCase(operationId).snakeCase}_response.dart';
    _writeFile(p.join(outputDirectory, 'responses', fileName), code);
  }

  /// Writes a client file.
  void writeClient(String tag, String code) {
    final fileName = '${ReCase(tag).snakeCase}_api_client.dart';
    _writeFile(p.join(outputDirectory, 'clients', fileName), code);
  }

  /// Writes a provider file.
  void writeProvider(String tag, String code) {
    final fileName = '${ReCase(tag).snakeCase}_providers.dart';
    _writeFile(p.join(outputDirectory, 'providers', fileName), code);
  }

  /// Writes the barrel file (api.dart).
  void writeBarrel(List<String> modelNames, List<String> responseNames,
      List<String> clientNames, [List<String> providerNames = const []]) {
    final buffer = StringBuffer();
    buffer.writeln('// Generated by florval. Do not edit.');
    buffer.writeln();

    for (final name in modelNames) {
      buffer.writeln("export 'models/${ReCase(name).snakeCase}.dart';");
    }
    for (final name in responseNames) {
      buffer.writeln(
          "export 'responses/${ReCase(name).snakeCase}_response.dart';");
    }
    for (final name in clientNames) {
      buffer.writeln(
          "export 'clients/${ReCase(name).snakeCase}_api_client.dart';");
    }
    for (final name in providerNames) {
      buffer.writeln(
          "export 'providers/${ReCase(name).snakeCase}_providers.dart';");
    }

    _writeFile(p.join(outputDirectory, 'api.dart'), buffer.toString());
  }

  void _writeFile(String path, String content) {
    File(path).writeAsStringSync(content);
  }
}
