import 'package:recase/recase.dart';

import '../config/florval_config.dart';
import '../config/template_config.dart';
import '../model/api_endpoint.dart';
import '../utils/dart_identifier.dart';
import '../utils/import_collector.dart';

/// Generates Riverpod 3.x providers grouped by tag.
///
/// - GET endpoints → @riverpod Notifier with build() params
/// - POST/PUT/DELETE/PATCH → `Mutation<ResponseType>()` constant + optional helper
class ProviderGenerator {
  final TemplateConfig? templateConfig;
  final bool autoInvalidate;
  final RiverpodRetryConfig? retry;

  ProviderGenerator({
    this.templateConfig,
    this.autoInvalidate = false,
    this.retry,
  });

  /// Generates a provider file for a group of endpoints sharing a tag.
  String generate(String tag, List<FlorvalEndpoint> endpoints) {
    final buffer = StringBuffer();

    // Custom header
    if (templateConfig?.header != null) {
      buffer.writeln(templateConfig!.header);
      buffer.writeln();
    }

    // Imports
    _writeImports(buffer, tag, endpoints);
    buffer.writeln();

    // Part directive (for riverpod_generator — always needed for client provider)
    buffer.writeln("part '${ReCase(tag).snakeCase}_providers.g.dart';");
    buffer.writeln();

    // Client provider
    _writeClientProvider(buffer, tag);
    buffer.writeln();

    // Separate GET endpoints for cache invalidation references
    final getEndpoints =
        autoInvalidate ? endpoints.where((e) => e.method == 'GET').toList() : <FlorvalEndpoint>[];

    // Endpoint providers / mutations
    for (final endpoint in endpoints) {
      if (endpoint.method == 'GET' && endpoint.pagination != null) {
        _writePaginatedProvider(buffer, tag, endpoint);
        _writePaginatedMutation(buffer, tag, endpoint);
      } else if (endpoint.method == 'GET') {
        _writeGetProvider(buffer, tag, endpoint);
      } else {
        _writeMutationDefinition(buffer, endpoint);
        if (autoInvalidate) {
          _writeMutationHelper(buffer, tag, endpoint,
              getEndpoints: getEndpoints);
        }
      }
      buffer.writeln();
    }

    return buffer.toString();
  }

  void _writeImports(
      StringBuffer buffer, String tag, List<FlorvalEndpoint> endpoints) {
    final hasGetEndpoints = endpoints.any((e) => e.method == 'GET');
    final hasMutationEndpoints = endpoints.any((e) => e.method != 'GET');

    // Import dio if any endpoint uses multipart (for MultipartFile type)
    final hasMultipart = endpoints.any(
        (e) => e.requestBody != null && e.requestBody!.isMultipart);
    if (hasMultipart) {
      buffer.writeln("import 'package:dio/dio.dart';");
    }
    final hasPagination = endpoints.any((e) => e.pagination != null);
    if (hasMutationEndpoints || hasPagination) {
      buffer.writeln(
          "import 'package:riverpod/experimental/mutation.dart';");
    }
    // Always import riverpod_annotation (needed for client provider @riverpod + Ref)
    buffer.writeln(
        "import 'package:riverpod_annotation/riverpod_annotation.dart';");

    // Custom provider imports
    if (templateConfig != null) {
      for (final import_ in templateConfig!.providerImports) {
        buffer.writeln(import_);
      }
    }
    buffer.writeln();

    // Import pagination utilities if needed
    if (hasPagination) {
      buffer.writeln("import '../models/api_exception.dart';");
      buffer.writeln("import '../models/paginated_data.dart';");
    }

    // Import retry utility if configured
    if (retry != null && hasGetEndpoints) {
      buffer.writeln("import 'retry.dart';");
    }

    // Import client
    buffer.writeln(
        "import '../clients/${ReCase(tag).snakeCase}_api_client.dart';");

    // Import model types
    final modelImports = <String>{};
    final generatesMutationHelpers = autoInvalidate;

    for (final endpoint in endpoints) {
      _collectModelImports(endpoint, modelImports,
          includeMutationBody: generatesMutationHelpers);
    }

    for (final import_ in modelImports) {
      buffer.writeln("import '../models/$import_.dart';");
    }
    // Import responses via barrel with r prefix to avoid collision with models
    buffer.writeln("import '../api_responses.dart' as r;");
  }

  /// Generates the retry utility file content.
  String generateRetryUtility(RiverpodRetryConfig retry) {
    final buffer = StringBuffer();
    buffer.writeln('// Generated by florval. Do not edit.');
    buffer.writeln();
    buffer.writeln(
        '/// Retry function for Riverpod GET providers (linear backoff).');
    buffer.writeln('Duration? retry(int retryCount, Object error) {');
    buffer.writeln('  if (retryCount >= ${retry.maxAttempts}) return null;');
    buffer.writeln(
        '  return Duration(milliseconds: ${retry.delay} * (retryCount + 1));');
    buffer.writeln('}');
    return buffer.toString();
  }

  void _writeClientProvider(StringBuffer buffer, String tag) {
    final className = '${ReCase(tag).pascalCase}ApiClient';
    final providerName = '${ReCase(tag).camelCase}ApiClient';

    buffer.writeln('@riverpod');
    buffer.writeln('$className $providerName(Ref ref) {');
    buffer.writeln(
        "  throw UnimplementedError('Provide a Dio instance via override');");
    buffer.writeln('}');
  }

  void _writeGetProvider(
      StringBuffer buffer, String tag, FlorvalEndpoint endpoint) {
    final className = ReCase(endpoint.operationId).pascalCase;
    final responseType = 'r.${className}Response';
    final clientProvider = '${ReCase(tag).camelCase}ApiClientProvider';
    final methodName = ReCase(endpoint.operationId).camelCase;

    if (endpoint.deprecated) {
      buffer.writeln("@Deprecated('')");
    }
    if (retry != null) {
      buffer.writeln('@Riverpod(retry: retry)');
    } else {
      buffer.writeln('@riverpod');
    }
    buffer.writeln('class $className extends _\$$className {');
    buffer.writeln('  @override');

    // build() signature
    final buildParams = _buildBuildParams(endpoint);
    if (buildParams.isNotEmpty) {
      buffer.writeln('  FutureOr<$responseType> build({');
      for (final param in buildParams) {
        buffer.writeln('    $param');
      }
      buffer.writeln('  }) async {');
    } else {
      buffer.writeln('  FutureOr<$responseType> build() async {');
    }

    // build() body
    buffer.writeln('    final client = ref.watch($clientProvider);');
    buffer.write('    return client.$methodName(');
    final callArgs = _buildCallArgs(endpoint);
    if (callArgs.isNotEmpty) {
      buffer.write(callArgs);
    }
    buffer.writeln(');');
    buffer.writeln('  }');
    buffer.writeln('}');
  }

  void _writePaginatedProvider(
      StringBuffer buffer, String tag, FlorvalEndpoint endpoint) {
    final className = ReCase(endpoint.operationId).pascalCase;
    final responseType = 'r.${className}Response';
    final clientProvider = '${ReCase(tag).camelCase}ApiClientProvider';
    final methodName = ReCase(endpoint.operationId).camelCase;
    final pagination = endpoint.pagination!;
    final itemDartType = pagination.itemType.dartType;
    final cursorParam = ReCase(pagination.cursorParam).camelCase;
    // Page type = 200 response body type (e.g. SearchPetsPage, CommentPage)
    final pageDartType = endpoint.responses[200]?.type?.dartType ?? 'dynamic';
    final paginatedType = 'PaginatedData<$itemDartType, $pageDartType>';

    if (endpoint.deprecated) {
      buffer.writeln("@Deprecated('')");
    }
    if (retry != null) {
      buffer.writeln('@Riverpod(retry: retry)');
    } else {
      buffer.writeln('@riverpod');
    }
    buffer.writeln('class $className extends _\$$className {');

    // Instance fields for accumulating paginated state
    buffer.writeln('  final List<$itemDartType> _allItems = [];');
    buffer.writeln('  String? _nextCursor;');
    buffer.writeln('  bool _hasMore = true;');
    buffer.writeln();

    buffer.writeln('  @override');

    // build() signature — include non-cursor query params and path params
    final buildParams = _buildPaginatedBuildParams(endpoint);
    if (buildParams.isNotEmpty) {
      buffer.writeln('  FutureOr<$paginatedType> build({');
      for (final param in buildParams) {
        buffer.writeln('    $param');
      }
      buffer.writeln('  }) async {');
    } else {
      buffer.writeln(
          '  FutureOr<$paginatedType> build() async {');
    }

    // Reset state
    buffer.writeln('    _allItems.clear();');
    buffer.writeln('    _nextCursor = null;');
    buffer.writeln('    _hasMore = true;');
    buffer.writeln();

    // Initial fetch (without cursor param)
    buffer.writeln('    final client = ref.watch($clientProvider);');
    final initialCallArgs = _buildPaginatedInitialCallArgs(endpoint);
    buffer.writeln('    final response = await client.$methodName($initialCallArgs);');
    buffer.writeln();

    // Switch on Union type
    buffer.writeln('    switch (response) {');
    buffer.writeln(
        '      case ${responseType}Success(:final data):');
    buffer.writeln(
        '        _allItems.addAll(data.${ReCase(pagination.itemsField).camelCase});');
    buffer.writeln(
        '        _nextCursor = data.${ReCase(pagination.nextCursorField).camelCase};');
    buffer.writeln(
        '        _hasMore = data.${ReCase(pagination.nextCursorField).camelCase} != null;');
    buffer.writeln('        return PaginatedData(');
    buffer.writeln('          items: List.unmodifiable(_allItems),');
    buffer.writeln('          nextCursor: _nextCursor,');
    buffer.writeln('          hasMore: _hasMore,');
    buffer.writeln('          lastPage: data,');
    buffer.writeln('        );');
    buffer.writeln('      default:');
    buffer.writeln('        throw ApiException(response);');
    buffer.writeln('    }');
    buffer.writeln('  }');
    buffer.writeln();

    // loadNextPage() method — called by external Mutation helper
    buffer.writeln('  Future<$paginatedType> loadNextPage() async {');
    buffer.writeln('    if (!_hasMore || _nextCursor == null) return state.requireValue;');
    buffer.writeln();
    buffer.writeln('    final client = ref.read($clientProvider);');

    // Build call args with cursor
    final fetchMoreArgs = _buildPaginatedFetchMoreArgs(endpoint, cursorParam);
    buffer.writeln(
        '    final response = await client.$methodName($fetchMoreArgs);');
    buffer.writeln();
    buffer.writeln('    switch (response) {');
    buffer.writeln(
        '      case ${responseType}Success(:final data):');
    buffer.writeln(
        '        _allItems.addAll(data.${ReCase(pagination.itemsField).camelCase});');
    buffer.writeln(
        '        _nextCursor = data.${ReCase(pagination.nextCursorField).camelCase};');
    buffer.writeln(
        '        _hasMore = data.${ReCase(pagination.nextCursorField).camelCase} != null;');
    buffer.writeln('        final result = PaginatedData(');
    buffer.writeln('          items: List.unmodifiable(_allItems),');
    buffer.writeln('          nextCursor: _nextCursor,');
    buffer.writeln('          hasMore: _hasMore,');
    buffer.writeln('          lastPage: data,');
    buffer.writeln('        );');
    buffer.writeln('        state = AsyncData(result);');
    buffer.writeln('        return result;');
    buffer.writeln('      default:');
    buffer.writeln(
        '        throw ApiException(response);');
    buffer.writeln('    }');
    buffer.writeln('  }');
    buffer.writeln('}');
  }

  void _writePaginatedMutation(
      StringBuffer buffer, String tag, FlorvalEndpoint endpoint) {
    final className = ReCase(endpoint.operationId).pascalCase;
    final pagination = endpoint.pagination!;
    final itemDartType = pagination.itemType.dartType;
    final pageDartType = endpoint.responses[200]?.type?.dartType ?? 'dynamic';
    final paginatedType = 'PaginatedData<$itemDartType, $pageDartType>';
    final providerName = '${ReCase(endpoint.operationId).camelCase}Provider';
    final mutationName = 'fetchMore${className}Mutation';
    final helperName = 'fetchMore${className}';

    // Mutation constant
    buffer.writeln();
    buffer.writeln('/// Mutation for fetching more pages of ${endpoint.operationId}.');
    buffer.writeln('final $mutationName = Mutation<$paginatedType>();');

    // Helper function
    buffer.writeln();
    buffer.writeln('/// Executes fetchMore mutation for ${endpoint.operationId}.');
    buffer.writeln('Future<$paginatedType> $helperName(');
    buffer.writeln('  MutationTarget ref,');
    buffer.writeln(') async {');
    buffer.writeln('  return $mutationName.run(ref, (tsx) async {');
    buffer.writeln('    final notifier = tsx.get($providerName.notifier);');
    buffer.writeln('    return notifier.loadNextPage();');
    buffer.writeln('  });');
    buffer.writeln('}');
  }

  /// Build params for paginated provider's build() method.
  /// Excludes the cursor param (it's managed internally).
  List<String> _buildPaginatedBuildParams(FlorvalEndpoint endpoint) {
    final params = <String>[];
    final cursorParam = endpoint.pagination!.cursorParam;

    for (final p in endpoint.pathParameters) {
      final name = safeProviderParamName(p.dartName);
      params.add('required ${p.type.dartType} $name,');
    }
    for (final p in endpoint.queryParameters) {
      if (p.name == cursorParam) continue; // Skip cursor param
      final name = safeProviderParamName(p.dartName);
      if (p.isRequired) {
        params.add('required ${p.type.dartType} $name,');
      } else {
        params.add('${p.type.asNullable().dartType} $name,');
      }
    }

    return params;
  }

  /// Build call args for the initial fetch in build(), excluding cursor param.
  String _buildPaginatedInitialCallArgs(FlorvalEndpoint endpoint) {
    final args = <String>[];
    final cursorParam = endpoint.pagination!.cursorParam;

    for (final p in endpoint.pathParameters) {
      final safe = safeProviderParamName(p.dartName);
      args.add('${p.dartName}: $safe');
    }
    for (final p in endpoint.queryParameters) {
      if (p.name == cursorParam) continue;
      final safe = safeProviderParamName(p.dartName);
      args.add('${p.dartName}: $safe');
    }

    return args.join(', ');
  }

  /// Build call args for fetchMore, including cursor param.
  String _buildPaginatedFetchMoreArgs(
      FlorvalEndpoint endpoint, String cursorDartName) {
    final args = <String>[];

    for (final p in endpoint.pathParameters) {
      final safe = safeProviderParamName(p.dartName);
      args.add('${p.dartName}: $safe');
    }
    for (final p in endpoint.queryParameters) {
      if (p.name == endpoint.pagination!.cursorParam) {
        args.add('$cursorDartName: _nextCursor');
      } else {
        final safe = safeProviderParamName(p.dartName);
        args.add('${p.dartName}: $safe');
      }
    }

    return args.join(', ');
  }

  void _writeMutationDefinition(
      StringBuffer buffer, FlorvalEndpoint endpoint) {
    final className = ReCase(endpoint.operationId).pascalCase;
    final responseType = 'r.${className}Response';

    buffer.writeln('/// Mutation for ${endpoint.operationId} (${endpoint.method} ${endpoint.path})');
    if (endpoint.deprecated) {
      buffer.writeln("@Deprecated('')");
    }
    buffer.writeln('final ${ReCase(endpoint.operationId).camelCase}Mutation = Mutation<$responseType>();');
  }

  void _writeMutationHelper(
      StringBuffer buffer, String tag, FlorvalEndpoint endpoint,
      {List<FlorvalEndpoint> getEndpoints = const []}) {
    final className = ReCase(endpoint.operationId).pascalCase;
    final responseType = 'r.${className}Response';
    final clientProvider = '${ReCase(tag).camelCase}ApiClientProvider';
    final methodName = ReCase(endpoint.operationId).camelCase;
    final mutationName = '${ReCase(endpoint.operationId).camelCase}Mutation';
    final helperName = ReCase(endpoint.operationId).camelCase;

    // Build helper function signature
    final helperParams = _buildMutationParams(endpoint);

    buffer.writeln();
    if (getEndpoints.isNotEmpty) {
      buffer.writeln('/// Executes ${ReCase(endpoint.operationId).camelCase} mutation and invalidates related GET providers.');
    } else {
      buffer.writeln('/// Executes ${ReCase(endpoint.operationId).camelCase} mutation.');
    }
    if (endpoint.deprecated) {
      buffer.writeln("@Deprecated('')");
    }
    if (helperParams.isNotEmpty) {
      buffer.writeln('Future<$responseType> $helperName(');
      buffer.writeln('  MutationTarget ref, {');
      for (final param in helperParams) {
        buffer.writeln('  $param');
      }
      buffer.writeln('}) async {');
    } else {
      buffer.writeln('Future<$responseType> $helperName(');
      buffer.writeln('  MutationTarget ref,');
      buffer.writeln(') async {');
    }

    buffer.writeln('  return $mutationName.run(ref, (tsx) async {');
    buffer.writeln('    final client = tsx.get($clientProvider);');

    // Client method call
    final callArgs = _buildMutationCallArgs(endpoint);
    if (callArgs.isNotEmpty) {
      buffer.writeln('    final result = await client.$methodName($callArgs);');
    } else {
      buffer.writeln('    final result = await client.$methodName();');
    }

    // Invalidate GET providers
    for (final getEndpoint in getEndpoints) {
      final providerName =
          '${ReCase(getEndpoint.operationId).camelCase}Provider';
      buffer.writeln('    ref.container.invalidate($providerName);');
    }

    buffer.writeln('    return result;');
    buffer.writeln('  });');
    buffer.writeln('}');
  }

  /// Build params for GET provider's build() method.
  /// Path params → required, query params → optional or required based on spec.
  /// Parameter names that conflict with Riverpod reserved names (e.g. `state`)
  /// are suffixed with `Param`.
  List<String> _buildBuildParams(FlorvalEndpoint endpoint) {
    final params = <String>[];

    for (final p in endpoint.pathParameters) {
      final name = safeProviderParamName(p.dartName);
      params.add('required ${p.type.dartType} $name,');
    }
    for (final p in endpoint.queryParameters) {
      final name = safeProviderParamName(p.dartName);
      if (p.isRequired) {
        params.add('required ${p.type.dartType} $name,');
      } else {
        params.add('${p.type.asNullable().dartType} $name,');
      }
    }

    return params;
  }

  /// Build call arguments for the client method invocation in GET providers.
  /// Maps safe parameter names back to the original dartName for the client call.
  String _buildCallArgs(FlorvalEndpoint endpoint) {
    final args = <String>[];

    for (final p in endpoint.pathParameters) {
      final safe = safeProviderParamName(p.dartName);
      args.add('${p.dartName}: $safe');
    }
    for (final p in endpoint.queryParameters) {
      final safe = safeProviderParamName(p.dartName);
      args.add('${p.dartName}: $safe');
    }

    return args.isEmpty ? '' : args.join(', ');
  }

  /// Build params for mutation helper function.
  /// Path params + query params + request body.
  List<String> _buildMutationParams(FlorvalEndpoint endpoint) {
    final params = <String>[];

    for (final p in endpoint.pathParameters) {
      params.add('required ${p.type.dartType} ${p.dartName},');
    }
    for (final p in endpoint.queryParameters) {
      if (p.isRequired) {
        params.add('required ${p.type.dartType} ${p.dartName},');
      } else {
        params.add('${p.type.asNullable().dartType} ${p.dartName},');
      }
    }
    if (endpoint.requestBody != null) {
      final body = endpoint.requestBody!;
      if (body.isMultipart && body.formFields != null) {
        // Expand multipart form fields as individual parameters
        for (final field in body.formFields!) {
          if (field.isRequired) {
            params.add('required ${field.type.dartType} ${field.name},');
          } else {
            params.add('${field.type.asNullable().dartType} ${field.name},');
          }
        }
      } else {
        if (body.isRequired) {
          params.add('required ${body.type.dartType} body,');
        } else {
          params.add('${body.type.asNullable().dartType} body,');
        }
      }
    }

    return params;
  }

  /// Build call arguments for the client method invocation in mutation helpers.
  String _buildMutationCallArgs(FlorvalEndpoint endpoint) {
    final args = <String>[];

    for (final p in endpoint.pathParameters) {
      args.add('${p.dartName}: ${p.dartName}');
    }
    for (final p in endpoint.queryParameters) {
      args.add('${p.dartName}: ${p.dartName}');
    }
    if (endpoint.requestBody != null) {
      final body = endpoint.requestBody!;
      if (body.isMultipart && body.formFields != null) {
        for (final field in body.formFields!) {
          args.add('${field.name}: ${field.name}');
        }
      } else {
        args.add('body: body');
      }
    }

    return args.isEmpty ? '' : args.join(', ');
  }

  void _collectModelImports(FlorvalEndpoint endpoint, Set<String> imports,
      {bool includeMutationBody = true}) {
    // Only import request body types for mutation endpoints when helpers are generated.
    // GET endpoints don't have request bodies, so the guard only affects mutations.
    if (endpoint.requestBody != null &&
        !endpoint.requestBody!.isMultipart &&
        (endpoint.method == 'GET' || includeMutationBody)) {
      addTypeImport(imports, endpoint.requestBody!.type);
    }
    if (endpoint.pagination != null) {
      addTypeImport(imports, endpoint.pagination!.itemType);
      // Import the page type (e.g. SearchPetsPage, CommentPage) for PaginatedData<T, P>
      final pageType = endpoint.responses[200]?.type;
      if (pageType != null) {
        addTypeImport(imports, pageType);
      }
    }
    // Import types from path and query parameters (e.g. enum types)
    for (final p in endpoint.parameters) {
      addTypeImport(imports, p.type);
    }
  }

}
