import 'dart:io';

/// Result of running the init command.
enum InitResult {
  created,
  alreadyExists,
}

/// Handles the `florval init` command logic.
class InitCommand {
  /// The config template content generated by `florval init`.
  static const configTemplate = '''florval:
  # Path to your OpenAPI spec file (required)
  schema_path: openapi.yaml

  # Output directory for generated code
  output_directory: lib/api/generated

  client:
    # Environment variable name for base URL
    base_url_env: API_BASE_URL
    # Default request timeout in milliseconds
    timeout: 30000

  riverpod:
    # Generate Riverpod providers
    enabled: true
    # Invalidate same-tag GET providers after mutations
    auto_invalidate: true
    # Exclude specific mutations from auto-invalidation by operationId (for optimistic updates)
    # exclude_auto_invalidate:
    #   - likePost          # operationId from OpenAPI spec
    #   - unlikePost
    retry:
      max_attempts: 3
      delay: 1000

    # Cursor-based pagination endpoints
    # pagination:
    #   defaults:
    #     cursor_param: after
    #     next_cursor_field: nextCursor
    #     items_field: items
    #   endpoints:
    #     - listUsers
    #     - listPosts
    #     - operation_id: listComments
    #       cursor_param: cursor
    #       next_cursor_field: next
    #       items_field: data
''';

  /// Runs the init command.
  ///
  /// Returns [InitResult.created] on success, or
  /// [InitResult.alreadyExists] if the file exists and [force] is false.
  static InitResult run({
    required String configPath,
    required bool force,
  }) {
    final file = File(configPath);

    if (file.existsSync() && !force) {
      return InitResult.alreadyExists;
    }

    file.writeAsStringSync(configTemplate);
    return InitResult.created;
  }
}
