import 'dart:io';

/// Result of running the init command.
enum InitResult {
  created,
  alreadyExists,
}

/// Handles the `florval init` command logic.
class InitCommand {
  /// The config template content generated by `florval init`.
  static const configTemplate = '''florval:
  # Path to your OpenAPI spec file (required)
  schema_path: openapi.yaml

  # Output directory for generated code
  output_directory: lib/api/generated

  client:
    # Environment variable name for base URL
    base_url_env: API_BASE_URL
    # Default request timeout in milliseconds
    timeout: 30000

  riverpod:
    # Generate Riverpod providers
    enabled: true
    # Invalidate same-tag GET providers after mutations
    auto_invalidate: true
    retry:
      max_attempts: 3
      delay: 1000

    # Cursor-based pagination endpoints
    # pagination:
    #   - operation_id: listItems
    #     cursor_param: after
    #     next_cursor_field: nextCursor
    #     items_field: items

  # templates:
  #   header: "// Custom header"
  #   model_imports: []
  #   client_imports: []
  #   provider_imports: []
''';

  /// Runs the init command.
  ///
  /// Returns [InitResult.created] on success, or
  /// [InitResult.alreadyExists] if the file exists and [force] is false.
  static InitResult run({
    required String configPath,
    required bool force,
  }) {
    final file = File(configPath);

    if (file.existsSync() && !force) {
      return InitResult.alreadyExists;
    }

    file.writeAsStringSync(configTemplate);
    return InitResult.created;
  }
}
